const PokerData = [
  {
    title: "A",
    icon: <i className="fas fa-gem" />,
    steptitle: "STEP1:",
    stepdetail: " Get your money ready. $$$$$ ",
    backicon: <i className="fas fa-coins" />,
    initial: { opacity: 0, x: -100 },
    animate: { opacity: 1, x: 0 },
  },
  {
    title: "5",
    icon: <i className="fas fa-fire" />,
    steptitle: "STEP2:",
    stepdetail: " Bring a fearless hreat. $$$$$ ",
    backicon: <i className="fas fa-hand-holding-heart" />,
    initial: { opacity: 0, y: -100 },
    animate: { opacity: 1, y: 0 },
  },
  {
    title: "Q",
    icon: <i className="fas fa-hat-wizard" />,
    steptitle: "STEP3:",
    stepdetail: " Never look back. $(important)$ ",
    backicon: <i className="fas fa-eye-slash" />,
    initial: { opacity: 0, y: 100 },
    animate: { opacity: 1, y: 0 },
  },
  {
    title: "K",
    icon: <i className="fas fa-dragon" />,
    steptitle: "STEP4:",
    stepdetail: " Enter the Poker World ! $$$$$ ",
    backicon: <i className="fas fa-door-open" />,
    initial: { opacity: 0, x: 100 },
    animate: { opacity: 1, x: 0 },
  },
  // {
  //   title: "$",
  //   icon: <i className="fas fa-ghost" />,
  //   initial: { opacity: 0, rotate: 0 },
  //   animate: { opacity: 1, rotate: 360 },
  // },
];
export default PokerData;
